<<<<<<< HEAD
# Generated by Django 2.2.6 on 2019-11-04 21:11

import django.core.validators
from django.db import migrations, models
=======
# Generated by Django 2.2.6 on 2019-11-04 22:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> e5478ff8ba84e84092c1c7d45f6a0dbdf7d9d36e


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> e5478ff8ba84e84092c1c7d45f6a0dbdf7d9d36e
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('max_capacity', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('opening_time', models.IntegerField()),
                ('closing_time', models.IntegerField()),
=======
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> e5478ff8ba84e84092c1c7d45f6a0dbdf7d9d36e
            ],
        ),
    ]
