# Generated by Django 2.2.6 on 2019-11-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_Item',
            new_name='Menu',
        ),
    ]
