# Generated by Django 2.2.6 on 2019-11-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191106_1433'),
        ('main_app', '0002_auto_20191107_1319'),
    ]

    operations = [
    ]
