# Generated by Django 2.2.6 on 2019-11-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191106_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
