# Generated by Django 2.2.6 on 2019-11-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191104_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Menu_Item',
        ),
    ]
