# Generated by Django 2.2.6 on 2019-11-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_20191107_1513'),
        ('main_app', '0007_auto_20191107_1526'),
    ]

    operations = [
    ]
